[profile.default]
src = 'src'
test = 'tests/'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = []
solc = '0.8.28'
ffi = true
fs_permissions = [{ access = "write", path = "./reports" }]
evm_version = 'shanghai'
optimizer = true
bytecode_hash = "none"

[profile.deploy]

[profile.sonic]
evm_version = 'cancun'

[profile.monad]
network = 'monad'

[rpc_endpoints]
celo = "${RPC_CELO}"
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
fantom = "${RPC_FANTOM}"
harmony = "${RPC_HARMONY}"
base = "${RPC_BASE}"
zkevm = "${RPC_ZKEVM}"
gnosis = "${RPC_GNOSIS}"
bnb = "${RPC_BNB}"
scroll = "${RPC_SCROLL}"
linea = "${RPC_LINEA}"
sonic = "${RPC_SONIC}"
ink = "${RPC_INK}"
plasma = "${RPC_PLASMA}"
mantle = "${RPC_MANTLE}"
megaeth = "${RPC_MEGAETH}"
xlayer = "${RPC_XLAYER}"
monad = "${RPC_MONAD}"
arc = "${RPC_ARC}"

[etherscan]
ink = { key = "any", chainId = 57073, url = 'https://explorer.inkonchain.com/api' }

# See more config options https://github.com/gakonst/foundry/tree/master/config
